
SELECT * FROM TBCADLCT

SELECT TIPLCT, LINLCT,CODTRM,INDDEB, INDCRD,MOVDEB,MOVCRD,STAREG,IDEPRE FROM TBCADLCT

INSERT INTO TBCADLCT (TIPLCT, TIPLIN,CODTRM,CODTAR,VEREXI,AGRLCT,INDDEB, INDCRD,MOVDEB,MOVCRD,STAREG,IDEPRE,VALLMT, VALSLD)
            VALUES   (    11,      1,     1,     0,     0,     0,     2,      3,     9,     9,    22,     0,     1,      1)
INSERT INTO TBCADLCT (TIPLCT, TIPLIN,CODTRM,CODTAR,VEREXI,AGRLCT,INDDEB, INDCRD,MOVDEB,MOVCRD,STAREG,IDEPRE,VALLMT, VALSLD)
            VALUES   (    11,      2,     1,     4,     0,     0,     2,      0,    10,     0,    22,     0,     1,      1)

INSERT INTO TBCADLCT (TIPLCT, TIPLIN,CODTRM,CODTAR,VEREXI,AGRLCT,INDDEB, INDCRD,MOVDEB,MOVCRD,STAREG,IDEPRE,VALLMT, VALSLD)
            VALUES   (    11,      1,     2,     0,     0,     0,     3,      2,     9,     9,    23,     0,     1,      1)
INSERT INTO TBCADLCT (TIPLCT, TIPLIN,CODTRM,CODTAR,VEREXI,AGRLCT,INDDEB, INDCRD,MOVDEB,MOVCRD,STAREG,IDEPRE,VALLMT, VALSLD)
            VALUES   (    11,      2,     2,     4,     0,     0,     0,      2,     0,    10,    23,     0,     1,      1)

INSERT INTO TBCADLCT (TIPLCT, TIPLIN,CODTRM,CODTAR,VEREXI,AGRLCT,INDDEB, INDCRD,MOVDEB,MOVCRD,STAREG,IDEPRE,VALLMT, VALSLD)
            VALUES   (    11,      1,     3,     0,     0,     0,     3,      2,     9,     9,    25,     0,     1,      1)


INSERT INTO TBCADLCT (TIPLCT, TIPLIN,CODTRM,CODTAR,VEREXI,AGRLCT,INDDEB, INDCRD,MOVDEB,MOVCRD,STAREG,IDEPRE,VALLMT, VALSLD)
            VALUES   (    21,      1,     1,     0,     0,     0,     2,      1,     1,     1,    21,     0,     1,      1)
INSERT INTO TBCADLCT (TIPLCT, TIPLIN,CODTRM,CODTAR,VEREXI,AGRLCT,INDDEB, INDCRD,MOVDEB,MOVCRD,STAREG,IDEPRE,VALLMT, VALSLD)
            VALUES   (    21,      2,     1,     3,     0,     0,     2,      0,     1,     2,    21,     0,     1,      1)

INSERT INTO TBCADLCT (TIPLCT, TIPLIN,CODTRM,CODTAR,VEREXI,AGRLCT,INDDEB, INDCRD,MOVDEB,MOVCRD,STAREG,IDEPRE,VALLMT, VALSLD)
            VALUES   (    21,      1,     2,     0,     0,     0,     1,      2,     1,     1,    23,     0,     1,      1)
INSERT INTO TBCADLCT (TIPLCT, TIPLIN,CODTRM,CODTAR,VEREXI,AGRLCT,INDDEB, INDCRD,MOVDEB,MOVCRD,STAREG,IDEPRE,VALLMT, VALSLD)
            VALUES   (    21,      2,     2,     3,     0,     0,     0,      2,     2,     1,    23,     0,     1,      1)

INSERT INTO TBCADLCT (TIPLCT, TIPLIN,CODTRM,CODTAR,VEREXI,AGRLCT,INDDEB, INDCRD,MOVDEB,MOVCRD,STAREG,IDEPRE,VALLMT, VALSLD)
            VALUES   (    21,      1,     3,     0,     0,     0,     1,      2,     1,     1,    25,     0,     1,      1)


INSERT INTO TBCADLCT (TIPLCT, TIPLIN,CODTRM,CODTAR,VEREXI,AGRLCT,INDDEB, INDCRD,MOVDEB,MOVCRD,STAREG,IDEPRE,VALLMT, VALSLD)
            VALUES   (    22,      1,     1,     0,     0,     0,     2,      2,     1,     1,    21,     0,     1,      1)
INSERT INTO TBCADLCT (TIPLCT, TIPLIN,CODTRM,CODTAR,VEREXI,AGRLCT,INDDEB, INDCRD,MOVDEB,MOVCRD,STAREG,IDEPRE,VALLMT, VALSLD)
            VALUES   (    22,      2,     1,     9,     0,     0,     2,      2,     1,     2,    21,     0,     1,      1)
INSERT INTO TBCADLCT (TIPLCT, TIPLIN,CODTRM,CODTAR,VEREXI,AGRLCT,INDDEB, INDCRD,MOVDEB,MOVCRD,STAREG,IDEPRE,VALLMT, VALSLD)
            VALUES   (    22,      1,     2,     0,     0,     0,     2,      2,     1,     1,    23,     0,     1,      1)
INSERT INTO TBCADLCT (TIPLCT, TIPLIN,CODTRM,CODTAR,VEREXI,AGRLCT,INDDEB, INDCRD,MOVDEB,MOVCRD,STAREG,IDEPRE,VALLMT, VALSLD)
            VALUES   (    22,      2,     2,     9,     0,     0,     2,      2,     2,     1,    23,     0,     1,      1)
INSERT INTO TBCADLCT (TIPLCT, TIPLIN,CODTRM,CODTAR,VEREXI,AGRLCT,INDDEB, INDCRD,MOVDEB,MOVCRD,STAREG,IDEPRE,VALLMT, VALSLD)
            VALUES   (    22,      1,     3,     0,     0,     0,     2,      2,     1,     1,    25,     0,     1,      1)

