
SELECT * FROM TBCADLCT

SELECT 'INSERT INTO TBCADLCT (TIPLCT, LINLCT,CODTRM,NUMORD,INDDEB, INDCRD,MOVDEB,MOVCRD,STAREG,IDEPRE) VALUES (' + CONVERT(VARCHAR,TIPLCT)+
 +',' + CONVERT(VARCHAR(3),LINLCT)
 +',' + CONVERT(VARCHAR,CODTRM)
 +',' + CONVERT(VARCHAR,NUMORD)
 +',' + CONVERT(VARCHAR,INDDEB)
 +',' + CONVERT(VARCHAR,INDCRD)
 +',' + CONVERT(VARCHAR,MOVDEB)
 +','+ CONVERT(VARCHAR,MOVCRD)
 +',' + CONVERT(VARCHAR,STAREG)
 +',' + CONVERT(VARCHAR,IDEPRE)+')'
 FROM TBCADLCT

 ORDER BY TIPLCT, LINLCT, CODTRM, NUMORD

INSERT INTO TBCADLCT (TIPLCT, LINLCT,CODTRM,NUMORD,INDDEB, INDCRD,MOVDEB,MOVCRD,STAREG,IDEPRE) VALUES (11,1,1,1,2,3,9,9,22,0)
INSERT INTO TBCADLCT (TIPLCT, LINLCT,CODTRM,NUMORD,INDDEB, INDCRD,MOVDEB,MOVCRD,STAREG,IDEPRE) VALUES (11,1,2,1,3,2,9,9,23,0)
INSERT INTO TBCADLCT (TIPLCT, LINLCT,CODTRM,NUMORD,INDDEB, INDCRD,MOVDEB,MOVCRD,STAREG,IDEPRE) VALUES (11,1,3,1,3,2,9,9,25,0)
INSERT INTO TBCADLCT (TIPLCT, LINLCT,CODTRM,NUMORD,INDDEB, INDCRD,MOVDEB,MOVCRD,STAREG,IDEPRE) VALUES (11,2,1,1,2,0,10,0,22,0)
INSERT INTO TBCADLCT (TIPLCT, LINLCT,CODTRM,NUMORD,INDDEB, INDCRD,MOVDEB,MOVCRD,STAREG,IDEPRE) VALUES (11,2,2,1,0,2,0,10,23,0)
INSERT INTO TBCADLCT (TIPLCT, LINLCT,CODTRM,NUMORD,INDDEB, INDCRD,MOVDEB,MOVCRD,STAREG,IDEPRE) VALUES (21,1,1,1,2,1,1,1,21,0)
INSERT INTO TBCADLCT (TIPLCT, LINLCT,CODTRM,NUMORD,INDDEB, INDCRD,MOVDEB,MOVCRD,STAREG,IDEPRE) VALUES (21,1,2,1,1,2,1,1,23,0)
INSERT INTO TBCADLCT (TIPLCT, LINLCT,CODTRM,NUMORD,INDDEB, INDCRD,MOVDEB,MOVCRD,STAREG,IDEPRE) VALUES (21,1,3,1,1,2,1,1,25,0)
INSERT INTO TBCADLCT (TIPLCT, LINLCT,CODTRM,NUMORD,INDDEB, INDCRD,MOVDEB,MOVCRD,STAREG,IDEPRE) VALUES (21,2,1,1,2,0,1,2,21,0)
INSERT INTO TBCADLCT (TIPLCT, LINLCT,CODTRM,NUMORD,INDDEB, INDCRD,MOVDEB,MOVCRD,STAREG,IDEPRE) VALUES (21,2,2,1,0,2,2,1,23,0)
INSERT INTO TBCADLCT (TIPLCT, LINLCT,CODTRM,NUMORD,INDDEB, INDCRD,MOVDEB,MOVCRD,STAREG,IDEPRE) VALUES (22,1,1,1,2,2,1,1,21,0)
INSERT INTO TBCADLCT (TIPLCT, LINLCT,CODTRM,NUMORD,INDDEB, INDCRD,MOVDEB,MOVCRD,STAREG,IDEPRE) VALUES (22,1,2,1,2,2,1,1,23,0)
INSERT INTO TBCADLCT (TIPLCT, LINLCT,CODTRM,NUMORD,INDDEB, INDCRD,MOVDEB,MOVCRD,STAREG,IDEPRE) VALUES (22,1,3,1,2,2,1,1,25,0)
INSERT INTO TBCADLCT (TIPLCT, LINLCT,CODTRM,NUMORD,INDDEB, INDCRD,MOVDEB,MOVCRD,STAREG,IDEPRE) VALUES (22,2,1,1,2,2,1,2,21,0)
INSERT INTO TBCADLCT (TIPLCT, LINLCT,CODTRM,NUMORD,INDDEB, INDCRD,MOVDEB,MOVCRD,STAREG,IDEPRE) VALUES (22,2,2,1,2,2,2,1,23,0)

INSERT INTO TBCADLCT (TIPLCT, LINLCT,CODTRM,NUMORD,INDDEB, INDCRD,MOVDEB,MOVCRD,STAREG,IDEPRE) VALUES (11,1,1,1,2,3,9,9,22,0)
INSERT INTO TBCADLCT (TIPLCT, LINLCT,CODTRM,NUMORD,INDDEB, INDCRD,MOVDEB,MOVCRD,STAREG,IDEPRE) VALUES (11,1,2,1,3,2,9,9,23,0)
INSERT INTO TBCADLCT (TIPLCT, LINLCT,CODTRM,NUMORD,INDDEB, INDCRD,MOVDEB,MOVCRD,STAREG,IDEPRE) VALUES (11,1,3,1,3,2,9,9,25,0)
INSERT INTO TBCADLCT (TIPLCT, LINLCT,CODTRM,NUMORD,INDDEB, INDCRD,MOVDEB,MOVCRD,STAREG,IDEPRE) VALUES (11,2,1,1,2,0,10,0,22,0)
INSERT INTO TBCADLCT (TIPLCT, LINLCT,CODTRM,NUMORD,INDDEB, INDCRD,MOVDEB,MOVCRD,STAREG,IDEPRE) VALUES (11,2,2,1,0,2,0,10,23,0)
INSERT INTO TBCADLCT (TIPLCT, LINLCT,CODTRM,NUMORD,INDDEB, INDCRD,MOVDEB,MOVCRD,STAREG,IDEPRE) VALUES (21,1,1,1,2,1,1,1,21,0)
INSERT INTO TBCADLCT (TIPLCT, LINLCT,CODTRM,NUMORD,INDDEB, INDCRD,MOVDEB,MOVCRD,STAREG,IDEPRE) VALUES (21,1,2,1,1,2,1,1,23,0)
INSERT INTO TBCADLCT (TIPLCT, LINLCT,CODTRM,NUMORD,INDDEB, INDCRD,MOVDEB,MOVCRD,STAREG,IDEPRE) VALUES (21,1,3,1,1,2,1,1,25,0)
INSERT INTO TBCADLCT (TIPLCT, LINLCT,CODTRM,NUMORD,INDDEB, INDCRD,MOVDEB,MOVCRD,STAREG,IDEPRE) VALUES (21,2,1,1,2,0,1,2,21,0)
INSERT INTO TBCADLCT (TIPLCT, LINLCT,CODTRM,NUMORD,INDDEB, INDCRD,MOVDEB,MOVCRD,STAREG,IDEPRE) VALUES (21,2,2,1,0,2,2,1,23,0)
INSERT INTO TBCADLCT (TIPLCT, LINLCT,CODTRM,NUMORD,INDDEB, INDCRD,MOVDEB,MOVCRD,STAREG,IDEPRE) VALUES (22,1,1,1,2,2,1,1,21,0)
INSERT INTO TBCADLCT (TIPLCT, LINLCT,CODTRM,NUMORD,INDDEB, INDCRD,MOVDEB,MOVCRD,STAREG,IDEPRE) VALUES (22,1,2,1,2,2,1,1,23,0)
INSERT INTO TBCADLCT (TIPLCT, LINLCT,CODTRM,NUMORD,INDDEB, INDCRD,MOVDEB,MOVCRD,STAREG,IDEPRE) VALUES (22,1,3,1,2,2,1,1,25,0)
INSERT INTO TBCADLCT (TIPLCT, LINLCT,CODTRM,NUMORD,INDDEB, INDCRD,MOVDEB,MOVCRD,STAREG,IDEPRE) VALUES (22,2,1,1,2,2,1,2,21,0)
INSERT INTO TBCADLCT (TIPLCT, LINLCT,CODTRM,NUMORD,INDDEB, INDCRD,MOVDEB,MOVCRD,STAREG,IDEPRE) VALUES (22,2,2,1,2,2,2,1,23,0)    
INSERT INTO TBCADLCT (TIPLCT, TIPLIN,CODTRM,CODTAR,VEREXI,AGRLCT,INDDEB, INDCRD,MOVDEB,MOVCRD,STAREG,IDEPRE,VALLMT, VALSLD)
            VALUES   (    11,      1,     1,     0,     0,     0,     2,      3,     9,     9,    22,     0,     1,      1)
INSERT INTO TBCADLCT (TIPLCT, TIPLIN,CODTRM,CODTAR,VEREXI,AGRLCT,INDDEB, INDCRD,MOVDEB,MOVCRD,STAREG,IDEPRE,VALLMT, VALSLD)
            VALUES   (    11,      2,     1,     4,     0,     0,     2,      0,    10,     0,    22,     0,     1,      1)

INSERT INTO TBCADLCT (TIPLCT, TIPLIN,CODTRM,CODTAR,VEREXI,AGRLCT,INDDEB, INDCRD,MOVDEB,MOVCRD,STAREG,IDEPRE,VALLMT, VALSLD)
            VALUES   (    11,      1,     2,     0,     0,     0,     3,      2,     9,     9,    23,     0,     1,      1)
INSERT INTO TBCADLCT (TIPLCT, TIPLIN,CODTRM,CODTAR,VEREXI,AGRLCT,INDDEB, INDCRD,MOVDEB,MOVCRD,STAREG,IDEPRE,VALLMT, VALSLD)
            VALUES   (    11,      2,     2,     4,     0,     0,     0,      2,     0,    10,    23,     0,     1,      1)

INSERT INTO TBCADLCT (TIPLCT, TIPLIN,CODTRM,CODTAR,VEREXI,AGRLCT,INDDEB, INDCRD,MOVDEB,MOVCRD,STAREG,IDEPRE,VALLMT, VALSLD)
            VALUES   (    11,      1,     3,     0,     0,     0,     3,      2,     9,     9,    25,     0,     1,      1)


INSERT INTO TBCADLCT (TIPLCT, TIPLIN,CODTRM,CODTAR,VEREXI,AGRLCT,INDDEB, INDCRD,MOVDEB,MOVCRD,STAREG,IDEPRE,VALLMT, VALSLD)
            VALUES   (    21,      1,     1,     0,     0,     0,     2,      1,     1,     1,    21,     0,     1,      1)
INSERT INTO TBCADLCT (TIPLCT, TIPLIN,CODTRM,CODTAR,VEREXI,AGRLCT,INDDEB, INDCRD,MOVDEB,MOVCRD,STAREG,IDEPRE,VALLMT, VALSLD)
            VALUES   (    21,      2,     1,     3,     0,     0,     2,      0,     1,     2,    21,     0,     1,      1)

INSERT INTO TBCADLCT (TIPLCT, TIPLIN,CODTRM,CODTAR,VEREXI,AGRLCT,INDDEB, INDCRD,MOVDEB,MOVCRD,STAREG,IDEPRE,VALLMT, VALSLD)
            VALUES   (    21,      1,     2,     0,     0,     0,     1,      2,     1,     1,    23,     0,     1,      1)
INSERT INTO TBCADLCT (TIPLCT, TIPLIN,CODTRM,CODTAR,VEREXI,AGRLCT,INDDEB, INDCRD,MOVDEB,MOVCRD,STAREG,IDEPRE,VALLMT, VALSLD)
            VALUES   (    21,      2,     2,     3,     0,     0,     0,      2,     2,     1,    23,     0,     1,      1)

INSERT INTO TBCADLCT (TIPLCT, TIPLIN,CODTRM,CODTAR,VEREXI,AGRLCT,INDDEB, INDCRD,MOVDEB,MOVCRD,STAREG,IDEPRE,VALLMT, VALSLD)
            VALUES   (    21,      1,     3,     0,     0,     0,     1,      2,     1,     1,    25,     0,     1,      1)


INSERT INTO TBCADLCT (TIPLCT, TIPLIN,CODTRM,CODTAR,VEREXI,AGRLCT,INDDEB, INDCRD,MOVDEB,MOVCRD,STAREG,IDEPRE,VALLMT, VALSLD)
            VALUES   (    22,      1,     1,     0,     0,     0,     2,      2,     1,     1,    21,     0,     1,      1)
INSERT INTO TBCADLCT (TIPLCT, TIPLIN,CODTRM,CODTAR,VEREXI,AGRLCT,INDDEB, INDCRD,MOVDEB,MOVCRD,STAREG,IDEPRE,VALLMT, VALSLD)
            VALUES   (    22,      2,     1,     9,     0,     0,     2,      2,     1,     2,    21,     0,     1,      1)
INSERT INTO TBCADLCT (TIPLCT, TIPLIN,CODTRM,CODTAR,VEREXI,AGRLCT,INDDEB, INDCRD,MOVDEB,MOVCRD,STAREG,IDEPRE,VALLMT, VALSLD)
            VALUES   (    22,      1,     2,     0,     0,     0,     2,      2,     1,     1,    23,     0,     1,      1)
INSERT INTO TBCADLCT (TIPLCT, TIPLIN,CODTRM,CODTAR,VEREXI,AGRLCT,INDDEB, INDCRD,MOVDEB,MOVCRD,STAREG,IDEPRE,VALLMT, VALSLD)
            VALUES   (    22,      2,     2,     9,     0,     0,     2,      2,     2,     1,    23,     0,     1,      1)
INSERT INTO TBCADLCT (TIPLCT, TIPLIN,CODTRM,CODTAR,VEREXI,AGRLCT,INDDEB, INDCRD,MOVDEB,MOVCRD,STAREG,IDEPRE,VALLMT, VALSLD)
            VALUES   (    22,      1,     3,     0,     0,     0,     2,      2,     1,     1,    25,     0,     1,      1)

