





SELECT A.*, DSCREC= ISNULL(B.NUMTAB,''), LGNUSU = ISNULL(C.LGNUSU,'') FROM TBTIPMOV (NOLOCK) A
INNER JOIN TBTABGER (NOLOCK) B ON (B.NUMREF =7 AND B.KEYCOD=A.STAREC)
 LEFT JOIN TBLGNUSU (NOLOCK) C ON (C.CODUSU = A.UPDUSU AND C.REGATV =1)


SELECT A.*, DSCREC= ISNULL(B.NUMTAB,''), LGNUSU = ISNULL(C.LGNUSU,'') FROM TBTIPMOV (NOLOCK) A
INNER JOIN TBTABGER (NOLOCK) B ON (B.NUMREF =7 AND B.KEYCOD=A.STAREC)
 LEFT JOIN TBLGNUSU (NOLOCK) C ON (C.CODUSU = A.UPDUSU AND C.REGATV =1)





