IF OBJECT_ID ( 'dbo.VWCADGER', 'V' ) IS NOT NULL
    DROP VIEW dbo.VWCADGER;
GO
/* ===================================================================================================
   Author : Agostin
     Date : 23/03/2022 08:10:53
 Objetivo : View de Registros do Cadastro Geral
 ==================================================================================================== */
CREATE VIEW dbo.VWCADGER
AS
    SELECT A.CODUSU
        ,A.CODATR
        ,D.DSCATR
        ,D.USELGN
        ,D.USETAR
        ,SRCUSU
        ,NOMGST = ISNULL(J.NOMUSU,'')
        ,NIVCFA
    	,CNTCTA = ISNULL(K.CNTCTA,0)
    	,CNTMAL = ISNULL(L.CNTMAL,0)
    	,CNTCEL = ISNULL(M.CNTCEL,0)
        ,STAUSU
        ,B.DSCSTA
        ,A.TIPUSU
        ,C.DSCTUS
        ,TIPPES
        ,ISNULL(H.DSCTAB,'') AS DSCPES
        ,CODPJU
        ,ISNULL(I.DSCTAB,'') AS DSCPJU
        ,NUMIRG
        ,CODCMF= dbo.FormatCMF(A.CODCMF)
        ,A.NOMUSU
        ,NOMMAE
        ,DATNAC
        ,ATRPPE
        ,DSCPPE = CASE WHEN ATRPPE=1 THEN 'Sim' else 'Não' END
        ,CTLOPE
        ,DSCOCO
        ,CODNAC
        ,DSCNAC = ISNULL(E.DSCTAB,'')
        ,A.STAREC
        ,ISNULL(G.DSCTAB,'') AS DSCREC
        ,A.DATCAD
        ,A.DATUPD
        ,A.UPDUSU
        ,LGNUSU = ISNULL(F.LGNUSU,'')
      FROM TBCADGER (NOLOCK) A
     INNER JOIN TBCADSTA (NOLOCK) B ON (B.CODSTA = A.STAUSU)
     INNER JOIN TBTIPUSU (NOLOCK) C ON (C.TIPUSU = A.TIPUSU)
     INNER JOIN TBTIPATR (NOLOCK) D ON (D.CODATR = A.CODATR)
     INNER JOIN TBTABGER (NOLOCK) E ON (E.NUMTAB=1 AND E.KEYCOD= A.CODNAC)
      LEFT JOIN TBLGNUSU (NOLOCK) F ON (F.CODUSU = A.UPDUSU AND F.REGATV=1)
     INNER JOIN TBTABGER (NOLOCK) G ON (G.NUMTAB=7 AND G.KEYCOD= A.STAREC)
     INNER JOIN TBTABGER (NOLOCK) H ON (H.NUMTAB=13 AND H.KEYTXT= A.TIPPES)
     INNER JOIN TBTABGER (NOLOCK) I ON (I.NUMTAB=8 AND I.KEYTXT= A.CODPJU)
      LEFT JOIN (SELECT CODUSU = USUPRO, NOMUSU = B1.NOMUSU + ' - ' + C1.DSCPRO
    FROM TBUSUPRO (NOLOCK) A1
    INNER JOIN TBCADGER (NOLOCK) B1 ON (B1.CODUSU = A1.CODUSU)
    INNER JOIN TBCADPRO (NOLOCK) C1 ON (C1.CODPRO = A1.CODPRO)) J ON (J.CODUSU = A.SRCUSU)
     LEFT JOIN (SELECT CODUSU, CNTCTA= COALESCE(COUNT(*),0 ) FROM TBCADCTA (NOLOCK) WHERE ORGCTA IN (1,3,4) AND STACTA=250 AND STAREC=1 GROUP BY CODUSU) K ON (K.CODUSU = A.CODUSU)
     LEFT JOIN (SELECT CODUSU, CNTMAL = COALESCE(COUNT(*),0) FROM TBCADEND (NOLOCK) WHERE STAREC=1 AND TIPEND=3 AND REGATV=1 GROUP BY CODUSU) L ON (L.CODUSU=A.CODUSU)
     LEFT JOIN (SELECT CODUSU, CNTCEL = COALESCE(COUNT(*),0) FROM TBCADCTO (NOLOCK) WHERE STAREC=1 AND TIPCTO=3 AND REGATV=1 GROUP BY CODUSU) M ON (M.CODUSU=A.CODUSU)


GO

