CREATE TABLE [dbo].[TBCADTAR] (
    [NIDTAR] INT      IDENTITY (1, 1) NOT NULL,
    [NIVCFG] TINYINT  DEFAULT ((2)) NOT NULL,
    [USUCFG] INT      NOT NULL,
    [CODTAR] TINYINT  NOT NULL,
    [CODBND] SMALLINT DEFAULT ((0)) NOT NULL,
    [TIPLIN] TINYINT  DEFAULT ((0)) NOT NULL,
    [MODCRT] SMALLINT DEFAULT ((0)) NOT NULL,
    [CODEXP] SMALLINT      DEFAULT ((0)) NOT NULL,
    [CODMOE] SMALLINT      DEFAULT ((1)) NOT NULL,
    [FMTCOB] TINYINT  DEFAULT ((1)) NOT NULL,
    [TARBAS] MONEY    DEFAULT ((0)) NOT NULL,
    [PCTTAR] MONEY    DEFAULT ((0)) NOT NULL,
    [VLRTAR] MONEY    DEFAULT ((0)) NOT NULL,
    [VLRINF] MONEY    DEFAULT ((0)) NOT NULL,
    [VLRMAX] MONEY    DEFAULT ((0)) NOT NULL,
    [APLEXP] TINYINT  DEFAULT ((0)) NOT NULL,
    [TARMAX] MONEY    DEFAULT ((0)) NOT NULL,
    [RSPTAR] TINYINT  DEFAULT ((2)) NOT NULL,
    [STAREC] TINYINT  DEFAULT ((1)) NOT NULL,
    [DATCAD] DATETIME DEFAULT (getdate()) NOT NULL,
    [DATUPD] DATE     DEFAULT (getdate()) NOT NULL,
    [UPDUSU] INT      DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_TBCADTAR] PRIMARY KEY CLUSTERED ([USUCFG] ASC, [CODTAR] ASC, [NIVCFG] ASC, [CODBND] ASC, [TIPLIN] ASC, [MODCRT] ASC),
    CONSTRAINT [FK_TBCADTAR_TBMODTAR] FOREIGN KEY ([MODCRT]) REFERENCES [dbo].[TBMODTAR] ([MODCRT]),
    CONSTRAINT [FK_TBCADTAR_TBTIPTAR] FOREIGN KEY ([CODTAR]) REFERENCES [dbo].[TBTIPTAR] ([CODTAR]), 
    CONSTRAINT [FK_TBCADTAR_TBTIPEXP] FOREIGN KEY ([CODEXP]) REFERENCES [TBTIPEXP]([TIPEXP])
);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Tariffs', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'TBCADTAR';

