CREATE TABLE [dbo].[TBEXPTAR] (
    [NIDEXP] INT      IDENTITY (1, 1) NOT NULL,
    [TIPEXP] SMALLINT  NOT NULL,
    [LVLAPL] TINYINT  NOT NULL,
    [VLRTAR] MONEY    DEFAULT ((0)) NOT NULL,
    [VLRMIN] MONEY    DEFAULT ((0)) NOT NULL,
    [VLRMAX] MONEY    DEFAULT ((0)) NOT NULL,
    [STAREC] TINYINT  DEFAULT ((1)) NOT NULL,
    [DATCAD] DATETIME DEFAULT (getdate()) NOT NULL,
    [DATUPD] DATETIME DEFAULT (getdate()) NOT NULL,
    [UPDUSU] INT      DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_TBEXPTAR] PRIMARY KEY CLUSTERED ([TIPEXP] ASC, [LVLAPL] ASC), 
    CONSTRAINT [FK_TBEXPTAR_TBTIPEXP] FOREIGN KEY (TIPEXP) REFERENCES [TBTIPEXP]([TIPEXP])
);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Expanded Tariff', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'TBEXPTAR';

