CREATE TABLE [dbo].[TBREGMEN] (
    [NIDMEN] INT      IDENTITY (1, 1) NOT NULL,
    [USUPRO] INT      NOT NULL,
    [CODUSU] INT      NOT NULL,
    [USRREF] INT      DEFAULT ((0)) NOT NULL,
    [TIPMEN] TINYINT  NOT NULL,
    [CODREF] INT      NOT NULL,
    [MODREG] TINYINT  DEFAULT ((1)) NOT NULL,
    [REGBXA] TINYINT  DEFAULT ((0)) NOT NULL,
    [STAMEN] SMALLINT NOT NULL,
    [SRCCAN] TINYINT  DEFAULT ((0)) NOT NULL,
    [NUMMES] TINYINT  DEFAULT ((0)) NOT NULL,
    [NUMANO] SMALLINT DEFAULT ((0)) NOT NULL,
    [NUMPCL] SMALLINT NOT NULL,
    [DATMEN] DATE     NOT NULL,
    [DATVCT] DATE     NOT NULL,
    [SIGOPE] SMALLINT DEFAULT ((1)) NOT NULL,
    [VLRCOB] MONEY    DEFAULT ((0)) NOT NULL,
    [LOTINS] INT      DEFAULT ((0)) NOT NULL,
    [NUMTEN] INT      DEFAULT ((0)) NOT NULL,
    [STAREC] TINYINT  DEFAULT ((1)) NOT NULL,
    [DATCAD] DATETIME DEFAULT (getdate()) NOT NULL,
    [DATUPD] DATETIME DEFAULT (getdate()) NOT NULL,
    [UPDUSU] INT      DEFAULT ((0)) NOT NULL,
    CONSTRAINT [FK_TBREGMEN_TBCADSTA] FOREIGN KEY ([STAMEN]) REFERENCES [dbo].[TBCADSTA] ([CODSTA]),
    CONSTRAINT [FK_TBREGMEN_TBCAGER] FOREIGN KEY ([CODUSU]) REFERENCES [dbo].[TBCADGER] ([CODUSU])
);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Monthly Payment', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'TBREGMEN';

