CREATE TABLE [dbo].[TBUSUPRO] (
    [USUPRO] INT      NOT NULL,
    [CODUSU] INT      NOT NULL,
    [CODPRO] SMALLINT NOT NULL,
    [APLINT] BIT      DEFAULT ((0)) NOT NULL,
    [VLRMIN] MONEY    DEFAULT ((0)) NOT NULL,
    [VLRMAX] MONEY    DEFAULT ((0)) NOT NULL,
    [APLRVC] BIT      DEFAULT ((0)) NOT NULL,
    [REGVCT] TINYINT  DEFAULT ((10)) NOT NULL,
    [APLCES] TINYINT  DEFAULT ((0)) NOT NULL,
    [APLTAD] TINYINT  DEFAULT ((0)) NOT NULL,
    [APLMEN] TINYINT  DEFAULT ((0)) NOT NULL,
    [VLRMEN] MONEY  DEFAULT ((0)) NOT NULL,
    [STAREC] TINYINT  DEFAULT ((1)) NOT NULL,
    [DATCAD] DATETIME DEFAULT (getdate()) NOT NULL,
    [DATUPD] DATETIME DEFAULT (getdate()) NOT NULL,
    [UPDUSU] INT      DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_TBUSUPRO] PRIMARY KEY CLUSTERED ([CODUSU] ASC, [CODPRO] ASC),
    CONSTRAINT [FK_TBUSUPRO_TBCADPRO] FOREIGN KEY ([CODPRO]) REFERENCES [dbo].[TBCADPRO] ([CODPRO])
);


GO
CREATE NONCLUSTERED INDEX [IX_TBUSUPRO_Column]
    ON [dbo].[TBUSUPRO]([USUPRO] ASC);

