CREATE TABLE [dbo].[TBLGNUSU] (
    [CODUSU] INT           NOT NULL,
    [LGNNUM] SMALLINT      IDENTITY (1, 1) NOT NULL,
    [LGNTYP] TINYINT       DEFAULT ((1)) NULL,
    [LGNUSU] VARCHAR (50)  NULL,
    [PSWUSU] VARCHAR (512) NULL,
    [RSTPSW] TINYINT       DEFAULT ((0)) NOT NULL,
    [ULTACE] DATETIME      NULL,
    [STAREC] TINYINT       DEFAULT ((1)) NOT NULL,
    [DATCAD] DATETIME      DEFAULT (getdate()) NOT NULL,
    [DATUPD] DATETIME      DEFAULT (getdate()) NOT NULL,
    [UPDUSU] INT           DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_TBLGNUSU] PRIMARY KEY CLUSTERED ([LGNNUM] ASC),
    CONSTRAINT [FK_TBLGNUSU_TBCADGER] FOREIGN KEY ([CODUSU]) REFERENCES [dbo].[TBCADGER] ([CODUSU])
);
